var data = [
    {
        name: "Sundorbon",
        info:
            "The Sundarbans is a mangrove area in the delta formed by the confluence of the Ganges, Brahmaputra and Meghna Rivers in the Bay of Bengal. It spans from the Hooghly River in India's state of West Bengal to the Baleswar River in Bangladesh.",
        detailInfo:
            "The Sundarbans is a mangrove area in the delta formed by the confluence of the Ganges, Brahmaputra and Meghna Rivers in the Bay of Bengal. It spans from the Hooghly River in India's state of West Bengal to the Baleswar River in Bangladesh. It comprises closed and open mangrove forests, agriculturally used land, mudflats and barren land, and is intersected by multiple tidal streams and channels. Four protected areas in the Sundarbans are enlisted as UNESCO World Heritage Sites, viz. Sundarbans National Park, Sundarbans West, Sundarbans South and Sundarbans East Wildlife Sanctuaries.",
        img: "https://i.ibb.co/sQVmZP0/sundorbon.png" ,
        id: 2,
        category: "destination",
        lat: 24.310577,
        lng: 91.725136,
    },
    {
        name: "Sajek",
        info:
            "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias facere reiciendis soluta voluptate a minima ratione ut doloremque fuga mollitia.",
        detailInfo:
            "The name of Sajek Valley came from the Sajek River that originates from Karnafuli river. The Sajek river works as a border between Bangladesh and India.Sajek is a union located in the north of Chittagong Hill Tracts. It's under Baghaichori Upazila in Rangamati hill district, it is situated 67 kilometres (42 mi) north-east from Khagrachhari town and 95 kilometres (59 mi) north from Rangamati city. The border of Bangladesh and Mizoram of India is 8 kilometres (5.0 mi) east from Sajek",
        img: "https://i.ibb.co/K2NRJGJ/Sajek.png",
        id: 3,
        category: "destination",
        lat: 21.9393505,
        lng: 89.1154938,
    },
    {
        name: "Srimongol",
        info:
            "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias facere reiciendis soluta voluptate a minima ratione ut doloremque fuga mollitia.",
        detailInfo:
            "It is said the name Sreemangal (or Srimangal) is named after Sri Das and Mangal Das; two brothers who settled on the banks of the Hail Haor. A copper plate of Raja Marundanath from the 11th century was found in Kalapur. During an excavation at Lamua, an ancient statue of Ananta Narayan was dug out. In 1454, the Nirmai Shiva Bari was built and still stands today. Srimangal thana was established in 1912. The central town later became a pourashava in 1935. In 1963, two peasants were killed by police officers which kicked off the Balishira peasant riots.",
        img: "https://i.ibb.co/HGCK0sq/Sreemongol.png" ,
        id: 4,
        category: "destination",
        lat: 23.3814064,
        lng: 92.2905528,
    },
    {
        title: "Light Bright airy stylish apt & safe peaceful stay",
        rating: 4.9,
        price: 34,
        img: "https://i.ibb.co/BCtQK5K/Rectangle-26.png",
        id: 5,
        numberOfPersonRated: 20,
        guests: 4,
        bedrooms: 2,
        beds: 2,
        bath: 2,
        total: 167,
        info: "With air conditioning kitchen.",
        cancellation: "Cancellation flexibility available.",
        category: "hotelInfo",
    },
    {
        title: "Apartment in Lost Panorama",
        rating: 4.8,
        price: 52,
        img: "https://i.ibb.co/mbcRHRB/Rectangle-27.png",
        id: 6,
        numberOfPersonRated: 10,
        guests: 4,
        bedrooms: 2,
        beds: 2,
        bath: 2,
        total: 167,
        info: "With air conditioning kitchen.",
        cancellation: "Cancellation flexibility available.",
        category: "hotelInfo",
    },
    {
        title: "AR Lounge & Pool (r&r + b&b)",
        rating: 4.9,
        price: 44,
        img: "https://i.ibb.co/g6pT27m/Rectangle-28.png",
        id: 7,
        numberOfPersonRated: 25,
        guests: 4,
        bedrooms: 2,
        beds: 2,
        bath: 2,
        total: 167,
        info: "With air conditioning kitchen.",
        cancellation: "Cancellation flexibility available.",
        category: "hotelInfo",
    },
];

export default data;
